### PR TITLE
Allow for remote repository inspection

### PR DESCRIPTION
**Pull request by miminar**
**Inspect remote images**

Added new flag to `docker inspect` command:

    $ docker inspect --remote <imageName>[:<tag>]...

Which inspects remote images. If a short name is given, all additional
registries will be queried until a match is found. Additional `[:TAG]`
suffix may further specify desired `<image>`.

This allows for remote inspection without downloading image layers.

Log Tag, Digest and Registry to stderr as debug messages. Need to pass
`-D` flag to Docker client to see them.

**List tags of remote repository**

Added new `--list` flag to `docker-tag` command:

    Usage:
        docker tag [-f] IMAGE[:TAG] [REGISTRYHOST/][USERNAME/]NAME[:TAG]
        docker tag -l [REGISTRYHOST/][USERNAME/]NAME...

    Tag an image or list remote tags

      -f, --force=false    Force
      --help=false         Print usage
      -l, --list=false     List tags of remote repositories

It produces following output:

    $ docker tag -l docker.io/fedora
    REPOSITORY          TAG                 IMAGE ID
    docker.io/fedora    20                  d7f0e75cf11fd6fe9fc3e676bb423f1504ea20da110d4d480f74cda8cb94f574
    docker.io/fedora    21                  e26efd418c4841f7299832fe7689de3e820d91a16bb4cff5b72eb9b09d712753
    docker.io/fedora    heisenbug           d7f0e75cf11fd6fe9fc3e676bb423f1504ea20da110d4d480f74cda8cb94f574
    docker.io/fedora    latest              e26efd418c4841f7299832fe7689de3e820d91a16bb4cff5b72eb9b09d712753
    docker.io/fedora    rawhide             f62b946038358811c82b9ce50601674a7e1b52ee742557429f244415064251b6

If a short name is given, list of additional registries will be queried
until a repository is found.

Quirks and TODOs:
 - By default V1 registry enpoints are queried because they provide tags
   with associated image IDs. If not available, V2 endpoint will be
   tried. In such a case the output will lack image IDs though.

### CODE REVIEW

**Comment by rhatdan** [comment]
Needs rebase.

**Comment by rhatdan** [comment]
@willmtemple

**Comment by miminar** [comment]
@rhatdan Rebased on top of registry patches (PR #84).

**Comment by rhatdan** [comment]
Merged

**Pull request closed without merging**
