### PR TITLE
Registry patches rebased for fedora

### PR DESCRIPTION
**Pull request by miminar**

### CODE REVIEW

**Comment by miminar** [comment]
This time there's remote inspection just on a server side.

**Comment by rhatdan** [comment]
Confirm a push to public Docker Registry should not be here.

Others merged.

**Comment by miminar** [comment]
I thought we want to ship the same patch set as for RHEL (https://bugzilla.redhat.com/show_bug.cgi?id=1243479).

**Comment by rhatdan** [comment]
I updated the bugzilla.  Daniel wanted the secrets patch so that he could play with RHEL images on Fedora, but I don't think we want to block pushes by default.  I updated the bugzilla with this.

**Comment by miminar** [comment]
Ok, thanks. I'll filter out the patch for Fedora from now on.

**Pull request closed without merging**
