### PR TITLE
Change error exit codes to help identify docker run errors from conta…

### PR DESCRIPTION
**Pull request by sallyom**
…iner errors

Signed-off-by: Sally O'Malley <somalley@redhat.com>

### CODE REVIEW

**Comment by sallyom** [comment]
I think this will eventually satisfy  https://bugzilla.redhat.com/show_bug.cgi?id=1097344 and https://bugzilla.redhat.com/show_bug.cgi?id=1097334

**Comment by rhatdan** [comment]
Please submit upstream.  You still have a bogus white space field in your patch, and you need to write a big comment on what you are doing. 

Cut and paste Regan's name to your pull request also. So you both get credit.

**Comment by sallyom** [comment]
will do.

**Comment by sallyom** [comment]
(Here are the test conditions I ran)
#/bin/bash
# Test changes to api/client/run.go error codes

echo 'docker run contained process exits 1, expect 1:'
docker run fedora /bin/false; echo $?
echo
# RESULT:    1

echo 'docker run non-existing image, expect 126:'
docker run foo; echo $?
echo
# RESULT:    Unable to find image 'foo:latest' locally
                       Pulling repository foo
                       126

echo 'docker run image ok, cmd does not exist, expect 126:'
docker run fedora foo; echo $?
echo
# RESULT:    exec: "foo": executable file not found in $PATH
                      126

echo 'docker run contained cmd could not execute, expect 127:'
docker run fedora /bin/foo; echo $?
echo 
# RESULT:    exec: "/bin/foo": stat /bin/foo: no such file or directory
                      127

echo 'docker run no errs, contained no errs, expect 0:'
docker run fedora /bin/true; echo $?
echo
# RESULT:    0

**Comment by sallyom** [comment]
I've replaced this pr with https://github.com/rhatdan/docker/pull/77

**Pull request closed without merging**
