### PR TITLE
Fix some exec-related crashes in integration tests

### PR DESCRIPTION
**Pull request by nalind**
Fixes a few things which caused errors while running integration tests:
* If we fail at any step of retrieving the client's login UID in getLoginUid(), return an error immediately after logging it, instead of proceeding.
* We're building dynamic binaries now, so os/user works, so we don't need to directly call into getpwuid() ourselves to avoid hitting a stub implementation.
* During "docker exec", the container ID may not be resolvable, so check for errors in attempting to read the container's configuration.
* Only close a syslog connection if we were successful in opening it.

### CODE REVIEW

**Comment by rhatdan** [comment]
Do you think we should fix this or just wait for docker-1.9?

**Comment by nalind** [comment]
If we're still using the 1.8 branch, we should fix it.  It's already fixed in the 1.9 branch.

**Comment by rhatdan** [comment]
I am thinking the next release to f23 will be docker-1.9 rather then an updated docker-1.8.

**Comment by nalind** [comment]
Okay, then.  Are we expecting to do any more for f22?

**Comment by rhatdan** [comment]
No I think we should end up pushing docker-1.9 their also.  If it is good enough to push to rhel7, it should be good enough for all supported versions of Fedora.

**Pull request merged**
