### PR TITLE
Rhel7 1.10 fixed

### PR DESCRIPTION
**Pull request by runcom**
Updated patches after @miminar review

### CODE REVIEW

**Comment by runcom** [comment]
@rhatdan you need to remove the last 4 commits in your `rhel7-10` branch and apply my 4 commits from here

**Comment by rhatdan** [comment]
LGTM Merged.

**Comment by rhatdan** [comment]
Runcom is there any way we could get rid of the confirm push and make this into an auth plugin?  IE Can you examine the image being pushed.   See if it is based on RHEL content and then confirm the push?

**Comment by runcom** [comment]
@rhatdan I'll look into moving that patch to an authz plugin and return to you

**Comment by rhatdan** [comment]
That would be a big improvement if we could and would elminate us from having to merge it every release.  Also we could ship it on Fedora and Centos. since it would only block pushing of rhel base images.  The problem will be defining a RHEL based image.  Currently I think the best way to do this is through the labels in the image, not sure if we can get that data from the plugin.  Second best option would be to look at the image name rhel* for example, but that is far less accurate.

**Comment by runcom** [comment]
The only problem I see with the authz plugin is that there is no way to force push. A flag from the cli would always be needed to force push thus the patch will still be there. Is the `--force` flag really needed? Can an admin just enable/disable the authz plugin to block push whether it needs it or not? This still suffer from the user that has to --force push

Looking at the labels is feasible because the plugin can inspect the given image to push and look for a particular label but I'm not sure everyone will put the base image label.
looking at name rhel* I agree is far far less accurante

**Comment by rhatdan** [comment]
@riekrh We would like to attempt to switch to using the authorization plugin for handling docker push of rhel content to docker.io, this would allow us to drop a patch.  @runcom believes we can do it but we might not be able to handle the docker push --force.   

Once we have it in authorization, users could enable and disable the plugin to eliminate the question. Also we can ask the question only for RHEL content.  IE If user wants to push fedora/centos/ubuntu no question.
Read above for more data.

**Comment by runcom** [comment]
@rhatdan I've realized the patch isn't looking for rhel7 base images, it just look for unqualified push or docker.io pushes

 So, I'm working on exposing the additional configured registries (--add-registry) in the docker api (there's already a patch but needs rework) in order to figure out how the daemon is configured and do logic outside the daemon - in authz plugin. This will be part of the --add-registry patch which we will keep.
This way we may know if someone is trying to push content to docker.io even if they push unqualified images (docker push rhel72basedimage)

As already said, client side --force is an issue unless we also patch docker (which we wouldn't)

**Comment by rhatdan** [comment]
Right I would like to get @riekrh to say we don't need force.  If you want to force, disable plugin.  We can easily document how to do this.
```
systemctl stop docker-rhel-nopush
systemctl disable docker-rhel-nopush
```

**Comment by runcom** [comment]
That will also need
```
systemctl restart docker
```

**Comment by riekrh** [comment]
I am ok with disabling the plugins instead of --force.

Keep in mind that the user story is two things though:
* Prevent situations where I accidentially push RHEL content to docker.io,
violating my subscription agreement.
* Prevent situations where I accidentially publish my internal code because
docker is the default registry.

Whatever meets those, is good.

Regards,

Daniel

On Fri, Jan 15, 2016 at 10:06 AM, Antonio Murdaca <notifications@github.com>
wrote:

> That will also need
>
> systemctl restart docker
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhatdan/docker/pull/169#issuecomment-171985758>.
>



-- 
Daniel Riek <riek@redhat.com>
* Sr. Director Systems Design & Engineering
* Red Hat Inc, Tel. +1-617-863-6776

**Comment by rhatdan** [comment]
Right the plugin should basically stop users from pushing rhel content to docker.io.  We might want to make this a little customizable, IE Allow users to specify  a list of urls that you are not allowed to push to, and a list of LABELS that should not be pushed.

**Comment by rhatdan** [comment]
Adding globs to make it easier, also

*.docker.io
rhel*
RHEL*

**Comment by runcom** [comment]
> IE Allow users to specify a list of urls that you are not allowed to push to,

This will be part of the plugin for blocking registry operations -> see https://github.com/runcom/registryacl look examples/config.toml
Is this new plugin going to do much the same but at just push level?

**Comment by runcom** [comment]
> IE Allow users to specify a list of urls that you are not allowed to push to,

This will be part of the plugin for blocking registry operations -> see https://github.com/runcom/registryacl look examples/config.toml
Is this new plugin going to do much the same but at just push level?

**Comment by rhatdan** [comment]
Pretty much, except in this case we want to examine the images being pushed.

**Comment by runcom** [comment]
Alright, I'll write down a Trello card for this plugin and collect requirements there

**Comment by rhatdan** [comment]
Great.

**Pull request closed without merging**
