### PR TITLE
hD hooks

### PR DESCRIPTION
**Pull request by sallyom**
Dockerhooks needs to be built without linkmode external.  Otherwise, it tries to depend on runtime/cgo.a and it segfaults when you try to run a container.

Signed-off-by: Sally O'Malley <somalley@redhat.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
LGTM. I tested it working with this patch.

**Comment by sallyom** [comment]
@mrunalp good news, thanks!

**Comment by rhatdan** [comment]
Merged.

**Comment by rhatdan** [comment]
If you guys get a chance could you check if the current docker hooks still works.  I made  a bunch of changes based on @vbatts comments.  I have no time to test right now.

**Pull request closed without merging**
