### PR TITLE
Generate distribution specific Dockerfile

### PR DESCRIPTION
**Pull request by sallyom**
Signed-off-by: Sally O'Malley <somalley@redhat.com>

Docker-DCO-1.1-Signed-off-by: Regan McCooey rmccooey27@aol.com (github: rhatdan)

### CODE REVIEW

**Comment by sallyom** [comment]
when I rebased against master instead of fedora-1.7  I
1) created a new PR
2) added those tab space diffs again.

**Comment by rhatdan** [comment]
Ok lets submit this upstream, but you need to improve your description of the pull request. We also need to reference the previous pull and close it.

**Comment by sallyom** [comment]
awesome, will do.

**Comment by sallyom** [comment]
I think i finally found a working combination of packages needed to build with Fedora.

**Comment by rhatdan** [comment]
Ok does make test succeed?

**Comment by sallyom** [comment]
'make test' works!  (A few tests fail but I think they are unrelated to these changes)

**Comment by rhatdan** [comment]
This has been sent upstream so closing.  @sallyom Is it working now?

**Comment by rhatdan** [comment]
@sallyom Could you send me a list of tests that are failing, and run a test without your patch to see if the tests all succeed.

**Comment by sallyom** [comment]
I'll send that list this afternoon, as I'm heading to the 'Women in IT' lunch now, however Lokesh thinks those tests are failing with Docker and not because of my patch :)

**Pull request closed without merging**
