### PR TITLE
Note API calls to syslog and the audit log

### PR DESCRIPTION
**Pull request by nalind**
These are changes from @alecbenson's PR#109 (for the fedora-1.8 branch), cherry-picked and with merge conflicts resolved.

We had to move from reading the host config directly from the container structure because the field is no longer public.  Instead, we take a bit of a hit by calling ContainerInspect(), which returns that data, along with some that we discard.

### CODE REVIEW

**Comment by nalind** [comment]
Oh, and I also made some changes to the placement of commas in the logged text.  Mistakes there are mine.

**Comment by alecbenson** [comment]
Thanks @nalind!  :+1:

**Comment by nalind** [comment]
Fixing some warnings from the recently-added lint validation checks and rebasing.

**Comment by nalind** [comment]
Now that we have a working os/user in Fedora, we don't need to call getpwuid() using cgo any more, and we don't need to bother with switching to getpwuid_r().
I'm getting a panic in the integration tests the second time we try to log something for a user with no login UID set (the kernel casts -1 to a UID, which is unsigned, which gives us 4294967295), and am trying to run that down.

**Comment by rhatdan** [comment]
Ok,

I merged your changes.

**Comment by rhatdan** [comment]
Please send new patch and I will merge with privous

**Comment by nalind** [comment]
Turns out it's not a bug in this patch set; the crash appears to be a bug in the libc that we're using.

**Pull request closed without merging**
