### PR TITLE
Refactor of PR #11405

### PR DESCRIPTION
**Pull request by alecbenson**
This is a port of PR #11405 code into the libnetwork codebase. 

Hopefully this will resolve the following bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1142357

### CODE REVIEW

**Comment by rhatdan** [comment]
@alecbenson Could you rebase against the latest fedora-1.7

**Comment by alecbenson** [comment]
Sure, I will do this as soon as I get home.

On Jun 17, 2015 5:22 PM, Daniel J Walsh <notifications@github.com> wrote:

@alecbenson<https://github.com/alecbenson> Could you rebase against the latest fedora-1.7

�

**Comment by alecbenson** [comment]
Rebased, this should merge cleanly now.

**Comment by rhatdan** [comment]
Good lets send this upstream.

**Comment by rhatdan** [comment]
Merged into rhel7 and fedora-1.7

**Pull request closed without merging**
