### PR TITLE
Registry patches rebased for rhel7

### PR DESCRIPTION
**Pull request by miminar**

### CODE REVIEW

**Comment by miminar** [comment]
Ouch, you've rebased in the meantime :(

**Comment by miminar** [comment]
Rebased again.

**Comment by rhatdan** [comment]
@miminar I was able to merge but a couple of big changes were still needed.

Had to comment out
```
		/*		if !endpoint.Mirror && (endpoint.Official || endpoint.Version == registry.APIVersion2) {
					if repoInfo.Official {
						s.trustService.UpdateBase()
					}
				}
		*/
```

in service.go and list.go since s.trustService no longer exists.

Also had to fix

```
// SearchRegistryForImages queries the registry for images matching
// term. authConfig is used to login.
func (daemon *Daemon) SearchRegistryForImages(term string,
	authConfig *cliconfig.AuthConfig,
	headers map[string][]string) ([]registry.SearchResultExt, error) {
	return daemon.RegistryService.Search(term, authConfig, headers, false)
}
```
in daemon.go.  Please verify everything is alright.

**Comment by rhatdan** [comment]
@miminar Is the UpdateBase above required?

**Comment by miminar** [comment]
@rhatdan I don't think so. It was removed from upstream's pull code also. I've removed the code from my registry patches as well.

**Comment by rhatdan** [comment]
Merged.

**Pull request closed without merging**
