### PR TITLE
Audit/System logging of Docker Daemon API calls

### PR DESCRIPTION
**Pull request by alecbenson**
This patch makes it much easier to determine what any container on a system is doing, and also provides valuable insight about how users on a system are interacting with the daemon. This PR is essentially a rebased version of [Docker PR #14446](https://github.com/docker/docker/pull/14446)

When an API call is made, an entry will be added to the syslog, and an audit log message will be generated.

### Notes About Integrating with Authentication
This patch has been designed to be easily integrated with the [authentication patch](https://github.com/docker/docker/pull/13994) being written by @nalind. 

Ideally, this integration will be accomplished by simply replacing the function calls to obtain the username and login UID of the user with the calls used in the authentication framework. Additionally, logic should be added to report whether or not the authentication was successful when logging. 

An example integration with @nalind's authentication framework can be found [here](https://github.com/alecbenson/docker/commit/9165b02a2dbb9655513d46026f322d37e3d1fdec). However, note that since the authentication code is still undergoing design changes, this example should be used as reference only and should not be copied line for line when the time comes to integrate with authentication. But nonetheless, integration should be relatively straightforward. 

CC @rhatdan @mheon

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind Need rebase makeHttpHandler has changed.

**Comment by nalind** [comment]
Can you merge from my fedora-1.8-audit-api-log branch instead?  The source branch for a pull request doesn't seem to be something I can modify, and this was originally Alec's PR.

**Comment by nalind** [comment]
Restarting as PR#131.

**Comment by rhatdan** [comment]
Do you want me to merge the 1.8 patches into the docker-1.9 branch?

If you want to join Alec's patches together with yours just leave his signoff.

**Comment by nalind** [comment]
This doesn't need to be merged to the 1.9 branch.  I thought that since you requested a rebase that we still needed a version for 1.8, and since I can't push to Alec's tree, I opened #131 with an updated version.  If we don't need this for 1.8, then we can close both this one and #131 without merging either.

**Comment by nalind** [comment]
Ah, those other two were merged, so we can close this one without merging (I can't, since I didn't open it).

**Pull request closed without merging**
