### PR TITLE
Registry patches rebased for Fedora

### PR DESCRIPTION
**Pull request by miminar**

### CODE REVIEW

**Comment by rhatdan** [comment]
@miminar these do not apply.

**Comment by miminar** [comment]
@rhatdan can you please take a look at:

    ---> Making bundle: dynbinary (in bundles/1.9.0-dev/dynbinary)
    Created binary: bundles/1.9.0-dev/dynbinary/dockerinit-1.9.0-dev
    Building: bundles/1.9.0-dev/dynbinary/docker-1.9.0-dev
    # github.com/docker/docker/daemon/graphdriver/devmapper
    .gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/deviceset.go:1647: undefined: info in info.Exists
    build failed

(current fedora-1.9)

**Comment by rhatdan** [comment]
Yes I am working with @rhvgoyal on fixing this issue.

**Comment by rhvgoyal** [comment]
@rhatdan That devicemapper patch you are carrying is upstream and there is no need to carry it explicitly. "devicemapper: Check loop devices of existing pool". Drop that patch and issue should be fixed.

**Comment by rhatdan** [comment]
Removed, thanks @rhvgoyal.  Removed two bogus patches.

**Comment by rhatdan** [comment]
Fixed up.

**Pull request closed without merging**
