### PR TITLE
cleanup, del/add libaudit-dev

### PR DESCRIPTION
**Pull request by sallyom**
Signed-off-by: Sally O'Malley <somalley@redhat.com>

### CODE REVIEW

**Comment by sallyom** [comment]
fixes 'No package libaudit-dev' error during build.   'audit-libs-devel' is in distro-specific json files

**Comment by rhatdan** [comment]
Fixed,

**Comment by sallyom** [comment]
@rhatdan, I missed the memo that I should be pulling from 1.10 :)

**Comment by rhatdan** [comment]
No stick to 1.9.  I have fixed the rhel7-1.9 and fedora-1.9 patche set to match except for the push request.  So please run the test again.

**Pull request closed without merging**
